name: Run Behave Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.11-slim

    # Required services
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install --system --dev
          apt-get update && apt-get install -y wget gnupg unzip curl procps

      - name: Install Google Chrome
        run: |
          wget -q https://dl.google.com/linux/linux_signing_key.pub -O /usr/share/keyrings/google-linux-signing-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-linux-signing-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" \
            > /etc/apt/sources.list.d/google-chrome.list
          apt-get update
          apt-get install -y google-chrome-stable

      - name: Install Chromedriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          wget -q https://storage.googleapis.com/chrome-for-testing-public/$CHROME_VERSION/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          mv chromedriver-linux64/chromedriver /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver

      - name: Start the service
        run: |
          setsid honcho start > server.log 2>&1 &
        env:
          DATABASE_URI: "postgresql+psycopg://postgres:postgres@postgres:5432/testdb"
      
      - name: Wait for the service to be ready
        run: |
          sleep 10
      
      - name: Display server logs
        if: failure()
        run: |
          cat server.log
      
      - name: Run Behave tests
        run: behave
        env:
          BASE_URL: "http://localhost:5000"
          DRIVER: "chrome"
      
      - name: Cleanup
        if: always()
        run: |
          pkill -TERM -g $$ || true
